(setq elfeed-feeds
      '(("https://nullprogram.com/feed/" blog coder)
	("https://nullprogram.com/feed/" blog coder)
	("https://jvns.ca/atom.xml" blog coder)
	("https://research.swtch.com/feed.atom" blog coder)
	("https://fabiensanglard.net/rss.xml" blog coder)
	("https://tiramisu.bearblog.dev/feed/" blog bear)
	("https://martinschuhmann.com/feed/" blog bear)
	("https://herman.bearblog.dev/feed/" blog bear)
	("https://cielbleu19.wordpress.com/feed/" blog wordpress)))
